from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .Event import Event, GameEvent, StatusEvent


# Frontier's journal appendix calls these the main-sequence star classes.  The
# warning feature intentionally uses the user's exact KGBFOAM definition: only
# these seven complete class codes are treated as KGBFOAM.
KGBFOAM_CLASSES = frozenset({"K", "G", "B", "F", "O", "A", "M"})


@dataclass(frozen=True)
class StarClassProfile:
    canonical_class: str
    normalized_class: str
    family: str
    family_en: str
    family_fr: str
    scoopable: bool | None
    appearance_en: str
    appearance_fr: str
    arrival_hazard_en: str
    arrival_hazard_fr: str
    jet_cone_supercharging: bool | None
    recommended_action_en: str
    recommended_action_fr: str


def _profile(
    canonical_class: str,
    *,
    family: str,
    family_en: str,
    family_fr: str,
    scoopable: bool | None,
    appearance_en: str,
    appearance_fr: str,
    arrival_hazard_en: str,
    arrival_hazard_fr: str,
    jet_cone_supercharging: bool | None,
    recommended_action_en: str,
    recommended_action_fr: str,
) -> StarClassProfile:
    return StarClassProfile(
        canonical_class=canonical_class,
        normalized_class=canonical_class.upper(),
        family=family,
        family_en=family_en,
        family_fr=family_fr,
        scoopable=scoopable,
        appearance_en=appearance_en,
        appearance_fr=appearance_fr,
        arrival_hazard_en=arrival_hazard_en,
        arrival_hazard_fr=arrival_hazard_fr,
        jet_cone_supercharging=jet_cone_supercharging,
        recommended_action_en=recommended_action_en,
        recommended_action_fr=recommended_action_fr,
    )


def _family_profiles(
    classes: tuple[str, ...],
    **kwargs: object,
) -> dict[str, StarClassProfile]:
    profiles: dict[str, StarClassProfile] = {}
    for star_class in classes:
        profile = _profile(star_class, **kwargs)  # type: ignore[arg-type]
        profiles[profile.normalized_class] = profile
    return profiles


# Star codes: Frontier-hosted Journal Manual v34, appendix "Star
# Descriptions", mirrored by elite-journal.readthedocs.io.  Mechanics and
# presentation wording are deliberately stored here rather than generated by
# a model.  Fuel-scoopability and the giant/supergiant exception are
# cross-checked against the established Elite Dangerous star catalogue:
# https://elite-dangerous.fandom.com/wiki/Stars
# Jet-cone guidance is cross-checked against the INARA travel/exploration guide:
# https://inara.cz/elite/squadron-document/7746/2927/
STAR_CLASS_PROFILES: dict[str, StarClassProfile] = {}

STAR_CLASS_PROFILES.update({
    "L": _profile(
        "L",
        family="brown_dwarf",
        family_en="class L brown dwarf",
        family_fr="naine brune de classe L",
        scoopable=False,
        appearance_en="cool, faint red-brown light",
        appearance_fr="lueur rouge-brun faible",
        arrival_hazard_en="the arrival is dark but has no unusual class-specific hazard beyond the exclusion zone",
        arrival_hazard_fr="l'arrivée est sombre mais sans danger particulier lié à la classe hors zone d'exclusion",
        jet_cone_supercharging=False,
        recommended_action_en="Confirm that the remaining fuel reaches a later scoopable star before continuing.",
        recommended_action_fr="Vérifiez que le carburant restant permet d'atteindre ensuite une étoile scoopable.",
    ),
    "T": _profile(
        "T",
        family="brown_dwarf",
        family_en="class T brown dwarf",
        family_fr="naine brune de classe T",
        scoopable=False,
        appearance_en="very faint brown-purple light",
        appearance_fr="lueur brun-violet très faible",
        arrival_hazard_en="the arrival is visually dark but mechanically routine if the exclusion zone is respected",
        arrival_hazard_fr="l'arrivée est visuellement sombre mais mécaniquement routinière si la zone d'exclusion est respectée",
        jet_cone_supercharging=False,
        recommended_action_en="Confirm that the remaining fuel reaches a later scoopable star before continuing.",
        recommended_action_fr="Vérifiez que le carburant restant permet d'atteindre ensuite une étoile scoopable.",
    ),
    "Y": _profile(
        "Y",
        family="brown_dwarf",
        family_en="class Y brown dwarf",
        family_fr="naine brune de classe Y",
        scoopable=False,
        appearance_en="exceptionally faint, easily overlooked light",
        appearance_fr="lueur exceptionnellement faible et facile à perdre de vue",
        arrival_hazard_en="the dark body can be hard to judge visually; keep the exclusion zone in view",
        arrival_hazard_fr="l'astre sombre peut être difficile à évaluer visuellement ; gardez la zone d'exclusion en vue",
        jet_cone_supercharging=False,
        recommended_action_en="Throttle down after arrival and confirm that the fuel reserve reaches a scoopable star.",
        recommended_action_fr="Réduisez les gaz à l'arrivée et confirmez que la réserve permet d'atteindre une étoile scoopable.",
    ),
})

STAR_CLASS_PROFILES.update({
    "TTS": _profile(
        "TTS",
        family="protostar",
        family_en="T Tauri protostar",
        family_fr="proto-étoile T Tauri",
        scoopable=False,
        appearance_en="orange-red light that can resemble a scoopable K or M star",
        appearance_fr="lueur rouge-orangé pouvant ressembler à une étoile K ou M scoopable",
        arrival_hazard_en="the arrival itself is routine; the resemblance is a fuel-planning trap, not an extra collision hazard",
        arrival_hazard_fr="l'arrivée elle-même est routinière ; la ressemblance est un piège de carburant, pas un risque de collision supplémentaire",
        jet_cone_supercharging=False,
        recommended_action_en="Do not expect the scoop to engage; verify the next reachable fuel star.",
        recommended_action_fr="N'attendez pas l'activation du scoop ; vérifiez la prochaine étoile à carburant accessible.",
    ),
    "AEBE": _profile(
        "AeBe",
        family="protostar",
        family_en="Herbig Ae/Be protostar",
        family_fr="proto-étoile Herbig Ae/Be",
        scoopable=False,
        appearance_en="bright white to blue-white young-star light",
        appearance_fr="lueur blanche à bleu-blanc d'une jeune étoile",
        arrival_hazard_en="the normal arrival is routine with a standard exclusion zone",
        arrival_hazard_fr="l'arrivée normale est routinière avec une zone d'exclusion standard",
        jet_cone_supercharging=False,
        recommended_action_en="Treat it as non-scoopable and confirm that the reserve reaches a later fuel star.",
        recommended_action_fr="Considérez-la comme non scoopable et confirmez que la réserve atteint une étoile à carburant ultérieure.",
    ),
})

STAR_CLASS_PROFILES.update(_family_profiles(
    ("W", "WN", "WNC", "WC", "WO"),
    family="wolf_rayet",
    family_en="Wolf-Rayet star",
    family_fr="étoile Wolf-Rayet",
    scoopable=False,
    appearance_en="very luminous blue-white light",
    appearance_fr="lueur bleu-blanc très lumineuse",
    arrival_hazard_en="the bright, large-looking arrival is normally routine if its exclusion zone is respected",
    arrival_hazard_fr="l'arrivée très lumineuse et apparemment vaste reste normalement routinière si sa zone d'exclusion est respectée",
    jet_cone_supercharging=False,
    recommended_action_en="Do not attempt to refuel; confirm that the remaining range reaches a scoopable star.",
    recommended_action_fr="Ne tentez pas de ravitailler ; confirmez que l'autonomie restante atteint une étoile scoopable.",
))

STAR_CLASS_PROFILES.update(_family_profiles(
    ("CS", "C", "CN", "CJ", "CH", "CHd", "MS", "S"),
    family="carbon_star",
    family_en="carbon or late-type giant star",
    family_fr="étoile carbonée ou géante tardive",
    scoopable=False,
    appearance_en="deep red to ruby, often large and luminous",
    appearance_fr="teinte rouge profond à rubis, souvent vaste et lumineuse",
    arrival_hazard_en="the unusual colour is not itself a special arrival danger; respect the normal exclusion zone",
    arrival_hazard_fr="la couleur inhabituelle n'est pas en soi un danger d'arrivée particulier ; respectez la zone d'exclusion normale",
    jet_cone_supercharging=False,
    recommended_action_en="Keep a fuel reserve for a later scoopable star.",
    recommended_action_fr="Gardez une réserve de carburant permettant d'atteindre une étoile scoopable ultérieure.",
))

STAR_CLASS_PROFILES.update(_family_profiles(
    ("D", "DA", "DAB", "DAO", "DAZ", "DAV", "DB", "DBZ", "DBV", "DO", "DOV", "DQ", "DC", "DCV", "DX"),
    family="white_dwarf",
    family_en="white dwarf",
    family_fr="naine blanche",
    scoopable=False,
    appearance_en="a compact, intensely bright white-blue remnant, sometimes with short jets",
    appearance_fr="rémanent compact blanc-bleu très intense, parfois accompagné de jets courts",
    arrival_hazard_en="normal arrival is not automatically dangerous, but the broad exclusion zone can sit close to a jet cone and an emergency drop there is hazardous",
    arrival_hazard_fr="l'arrivée normale n'est pas automatiquement dangereuse, mais la vaste zone d'exclusion peut frôler le cône et une sortie d'urgence à cet endroit est dangereuse",
    jet_cone_supercharging=True,
    recommended_action_en="Stay clear of the exclusion zone and use the cone only deliberately.",
    recommended_action_fr="Restez hors de la zone d'exclusion et n'utilisez le cône que volontairement.",
))

STAR_CLASS_PROFILES["N"] = _profile(
    "N",
    family="neutron_star",
    family_en="neutron star",
    family_fr="étoile à neutrons",
    scoopable=False,
    appearance_en="a tiny remnant with bright, often long jet cones",
    appearance_fr="rémanent minuscule aux cônes lumineux souvent longs",
    arrival_hazard_en="arrival clear of the jets is routine; a cone causes control disturbance and FSD wear, and dropping inside it is dangerous",
    arrival_hazard_fr="l'arrivée hors des jets est routinière ; un cône perturbe le contrôle et use le FSD, et y sortir de supercroisière est dangereux",
    jet_cone_supercharging=True,
    recommended_action_en="Enter a cone only intentionally in supercruise; otherwise keep it clear.",
    recommended_action_fr="N'entrez dans un cône que volontairement en supercroisière ; sinon, restez à l'écart.",
)

STAR_CLASS_PROFILES["H"] = _profile(
    "H",
    family="black_hole",
    family_en="black hole",
    family_fr="trou noir",
    scoopable=False,
    appearance_en="optically dark, visible mainly through gravitational lensing",
    appearance_fr="optiquement sombre, visible surtout par lentille gravitationnelle",
    arrival_hazard_en="the darkness is unfamiliar, but normal arrival is mechanically routine; excessive approach can still reach the exclusion zone",
    arrival_hazard_fr="l'obscurité est inhabituelle, mais l'arrivée normale est mécaniquement routinière ; une approche excessive peut tout de même atteindre la zone d'exclusion",
    jet_cone_supercharging=False,
    recommended_action_en="Throttle down, use the lensing to orient, and retain fuel for a scoopable star.",
    recommended_action_fr="Réduisez les gaz, utilisez la lentille pour vous orienter et gardez du carburant pour une étoile scoopable.",
)

STAR_CLASS_PROFILES["SUPERMASSIVEBLACKHOLE"] = _profile(
    "SupermassiveBlackHole",
    family="supermassive_black_hole",
    family_en="supermassive black hole",
    family_fr="trou noir supermassif",
    scoopable=False,
    appearance_en="a vast dark lensing distortion rather than a luminous surface",
    appearance_fr="vaste distorsion sombre par lentille plutôt qu'une surface lumineuse",
    arrival_hazard_en="normal arrival remains controlled, but a close approach can cause rapid heat build-up and reach the exclusion zone",
    arrival_hazard_fr="l'arrivée normale reste contrôlée, mais une approche rapprochée peut provoquer une montée rapide de chaleur et atteindre la zone d'exclusion",
    jet_cone_supercharging=False,
    recommended_action_en="Throttle down and avoid a close approach; retain fuel for a scoopable star.",
    recommended_action_fr="Réduisez les gaz et évitez l'approche rapprochée ; gardez du carburant pour une étoile scoopable.",
)

STAR_CLASS_PROFILES.update({
    "A_BLUEWHITESUPERGIANT": _profile(
        "A_BlueWhiteSuperGiant",
        family="giant_or_supergiant",
        family_en="A blue-white supergiant",
        family_fr="supergéante bleu-blanc de type A",
        scoopable=True,
        appearance_en="very large and intensely blue-white",
        appearance_fr="très vaste et intensément bleu-blanc",
        arrival_hazard_en="the scale is unusual but the normal arrival is routine if the large exclusion zone is respected",
        arrival_hazard_fr="l'échelle est inhabituelle mais l'arrivée normale est routinière si la vaste zone d'exclusion est respectée",
        jet_cone_supercharging=False,
        recommended_action_en="Throttle down, respect the exclusion zone, and refuel if planned.",
        recommended_action_fr="Réduisez les gaz, respectez la zone d'exclusion et ravitaillez si prévu.",
    ),
    "B_BLUEWHITESUPERGIANT": _profile(
        "B_BlueWhiteSuperGiant",
        family="giant_or_supergiant",
        family_en="B blue-white supergiant",
        family_fr="supergéante bleu-blanc de type B",
        scoopable=True,
        appearance_en="very large, hot, and brilliant blue-white",
        appearance_fr="très vaste, chaude et brillante, de couleur bleu-blanc",
        arrival_hazard_en="the scale and heat are notable; normal arrival is routine while the exclusion zone is respected",
        arrival_hazard_fr="l'échelle et la chaleur sont notables ; l'arrivée normale reste routinière tant que la zone d'exclusion est respectée",
        jet_cone_supercharging=False,
        recommended_action_en="Throttle down, watch heat, and refuel only at a comfortable distance.",
        recommended_action_fr="Réduisez les gaz, surveillez la chaleur et ne ravitaillez qu'à distance confortable.",
    ),
    "F_WHITESUPERGIANT": _profile(
        "F_WhiteSuperGiant",
        family="giant_or_supergiant",
        family_en="F white supergiant",
        family_fr="supergéante blanche de type F",
        scoopable=True,
        appearance_en="very large and bright white-yellow",
        appearance_fr="très vaste et brillante, de couleur blanc-jaune",
        arrival_hazard_en="the large apparent disk is unusual but normal arrival is routine outside the exclusion zone",
        arrival_hazard_fr="le disque apparent très vaste est inhabituel mais l'arrivée normale est routinière hors zone d'exclusion",
        jet_cone_supercharging=False,
        recommended_action_en="Throttle down, respect the exclusion zone, and refuel if planned.",
        recommended_action_fr="Réduisez les gaz, respectez la zone d'exclusion et ravitaillez si prévu.",
    ),
    "M_REDSUPERGIANT": _profile(
        "M_RedSuperGiant",
        family="giant_or_supergiant",
        family_en="M red supergiant",
        family_fr="supergéante rouge de type M",
        scoopable=True,
        appearance_en="enormous and red-orange",
        appearance_fr="immense et rouge-orangé",
        arrival_hazard_en="the scale is dramatic but the normal arrival is mechanically routine outside the exclusion zone",
        arrival_hazard_fr="l'échelle est impressionnante mais l'arrivée normale est mécaniquement routinière hors zone d'exclusion",
        jet_cone_supercharging=False,
        recommended_action_en="Throttle down, keep the exclusion zone visible, and refuel if needed.",
        recommended_action_fr="Réduisez les gaz, gardez la zone d'exclusion visible et ravitaillez si nécessaire.",
    ),
    "M_REDGIANT": _profile(
        "M_RedGiant",
        family="giant_or_supergiant",
        family_en="M red giant",
        family_fr="géante rouge de type M",
        scoopable=True,
        appearance_en="large and red-orange",
        appearance_fr="vaste et rouge-orangé",
        arrival_hazard_en="the large apparent disk is unusual but normal arrival is mechanically routine outside the exclusion zone",
        arrival_hazard_fr="le disque apparent très vaste est inhabituel mais l'arrivée normale est mécaniquement routinière hors zone d'exclusion",
        jet_cone_supercharging=False,
        recommended_action_en="Throttle down, respect the exclusion zone, and refuel if needed.",
        recommended_action_fr="Réduisez les gaz, respectez la zone d'exclusion et ravitaillez si nécessaire.",
    ),
    "K_ORANGEGIANT": _profile(
        "K_OrangeGiant",
        family="giant_or_supergiant",
        family_en="K orange giant",
        family_fr="géante orange de type K",
        scoopable=True,
        appearance_en="large and orange-yellow",
        appearance_fr="vaste et orange-jaune",
        arrival_hazard_en="the large apparent disk is unusual but normal arrival is mechanically routine outside the exclusion zone",
        arrival_hazard_fr="le disque apparent très vaste est inhabituel mais l'arrivée normale est mécaniquement routinière hors zone d'exclusion",
        jet_cone_supercharging=False,
        recommended_action_en="Throttle down, respect the exclusion zone, and refuel if needed.",
        recommended_action_fr="Réduisez les gaz, respectez la zone d'exclusion et ravitaillez si nécessaire.",
    ),
})

STAR_CLASS_PROFILES.update(_family_profiles(
    ("X", "RoguePlanet", "Nebula", "StellarRemnantNebula"),
    family="journal_placeholder",
    family_en="documented exotic or placeholder class",
    family_fr="classe exotique ou réservée du journal",
    scoopable=None,
    appearance_en="no verified in-game appearance is documented for this journal code",
    appearance_fr="aucune apparence en jeu vérifiée n'est documentée pour ce code du journal",
    arrival_hazard_en="class-level arrival mechanics are not documented and will not be invented",
    arrival_hazard_fr="les mécaniques d'arrivée liées à cette classe ne sont pas documentées et ne seront pas inventées",
    jet_cone_supercharging=None,
    recommended_action_en="Check the system map, keep a conservative fuel reserve, and proceed only when oriented.",
    recommended_action_fr="Consultez la carte système, gardez une réserve prudente et poursuivez seulement une fois orienté.",
))


OFFICIAL_NON_KGBFOAM_CLASSES = frozenset(
    profile.canonical_class for profile in STAR_CLASS_PROFILES.values()
)


def normalize_star_class(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    normalized = value.strip().upper()
    return normalized or None


def is_kgbfoam(value: object) -> bool:
    normalized = normalize_star_class(value)
    return normalized in KGBFOAM_CLASSES if normalized else False


def get_star_class_profile(value: object) -> StarClassProfile | None:
    normalized = normalize_star_class(value)
    if normalized is None:
        return None
    return STAR_CLASS_PROFILES.get(normalized)


def _fuel_hazard(language: Literal["en", "fr"]) -> str:
    if language == "fr":
        return "Risque réel de panne sèche si aucune étoile scoopable ne reste à portée."
    return "There is a real fuel-stranding risk if no scoopable star remains within range."


def format_star_warning(
    profile: StarClassProfile,
    language: Literal["en", "fr"],
) -> str:
    if language == "fr":
        if profile.scoopable is True:
            scoopability = "Scoopable malgré son code hors des sept classes KGBFOAM exactes."
        elif profile.scoopable is False:
            scoopability = f"Non scoopable. {_fuel_hazard('fr')}"
        else:
            scoopability = "Scoopabilité non documentée."
        jet = (
            " Surcharge par cône possible ; manœuvre à n'entreprendre que volontairement."
            if profile.jet_cone_supercharging is True
            else ""
        )
        return (
            f"Attention calme : prochaine étoile, {profile.family_fr}, code journal {profile.canonical_class}. "
            f"{scoopability} Aspect attendu : {profile.appearance_fr} ; {profile.arrival_hazard_fr}."
            f"{jet} {profile.recommended_action_fr}"
        )

    if profile.scoopable is True:
        scoopability = "It is scoopable despite being outside the seven exact KGBFOAM codes."
    elif profile.scoopable is False:
        scoopability = f"It is not scoopable. {_fuel_hazard('en')}"
    else:
        scoopability = "Its scoopability is not documented."
    jet = (
        " Jet-cone supercharging is possible and should be attempted only deliberately."
        if profile.jet_cone_supercharging is True
        else ""
    )
    return (
        f"Calm warning: next star, {profile.family_en}, journal code {profile.canonical_class}. "
        f"{scoopability} Expected appearance: {profile.appearance_en}; {profile.arrival_hazard_en}."
        f"{jet} {profile.recommended_action_en}"
    )


def format_unknown_class_warning(language: Literal["en", "fr"]) -> str:
    if language == "fr":
        return (
            "Attention calme : classification de la prochaine étoile inconnue. "
            "Aucune classe ne sera déduite. Vérifiez la carte et la réserve de carburant avant de poursuivre."
        )
    return (
        "Calm warning: the next star's classification is unknown. No class will be inferred. "
        "Check the map and fuel reserve before continuing."
    )


def configured_warning_language(config: dict[str, object]) -> Literal["en", "fr"]:
    language_values: list[object] = []
    characters = config.get("characters")
    active_index = config.get("active_character_index", 0)
    if isinstance(characters, list) and isinstance(active_index, int):
        if 0 <= active_index < len(characters) and isinstance(characters[active_index], dict):
            language_values.append(characters[active_index].get("personality_language"))
    language_values.append(config.get("tts_language"))
    for value in language_values:
        if not isinstance(value, str):
            continue
        normalized = value.strip().casefold()
        if normalized.startswith("fr") or "french" in normalized or "français" in normalized or "francais" in normalized:
            return "fr"
    return "en"


@dataclass(frozen=True)
class JumpTarget:
    name: str | None
    system_address: int | None
    star_class: object


@dataclass(frozen=True)
class JumpWarningDecision:
    cycle_id: int
    kind: Literal["known", "unknown"]
    trigger: Literal["fsd_charging", "start_jump"]
    target_name: str | None
    star_class: str | None
    profile: StarClassProfile | None


class NonKgbfoamJumpWarningController:
    """Pure local state machine for one warning per hyperspace charge cycle."""

    def __init__(self) -> None:
        self.current_target: JumpTarget | None = None
        self.charge_active = False
        self.charge_kind: Literal["hyperspace", "supercruise", "unknown"] | None = None
        self.cycle_sequence = 0
        self.active_cycle_id: int | None = None
        self.cycle_warned = False
        self.phase: Literal["idle", "charging", "countdown", "completed"] = "idle"

    @staticmethod
    def _address(value: object) -> int | None:
        return value if isinstance(value, int) and not isinstance(value, bool) else None

    @staticmethod
    def _name(value: object) -> str | None:
        if not isinstance(value, str):
            return None
        value = value.strip()
        return value or None

    def _begin_cycle(
        self,
        kind: Literal["hyperspace", "supercruise", "unknown"],
    ) -> None:
        self.cycle_sequence += 1
        self.active_cycle_id = self.cycle_sequence
        self.cycle_warned = False
        self.charge_kind = kind
        self.phase = "charging"

    def _target_for_status(self, status: dict[str, object]) -> JumpTarget | None:
        target = self.current_target
        destination = status.get("Destination")
        if not isinstance(destination, dict):
            return target

        destination_address = self._address(destination.get("System"))
        destination_name = self._name(destination.get("Name"))
        if target is None:
            return JumpTarget(destination_name, destination_address, None)

        address_mismatch = (
            destination_address is not None
            and target.system_address is not None
            and destination_address != target.system_address
        )
        name_mismatch = (
            destination_name is not None
            and target.name is not None
            and destination_name.casefold() != target.name.casefold()
        )
        if address_mismatch or (target.system_address is None and name_mismatch):
            # The cached FSDTarget is stale.  Preserve destination identity but
            # never carry its class over to a different target.
            return JumpTarget(destination_name, destination_address, None)
        return target

    def _decision_for_target(
        self,
        target: JumpTarget | None,
        *,
        trigger: Literal["fsd_charging", "start_jump"],
        warning_enabled: bool,
        unknown_warning_enabled: bool,
    ) -> JumpWarningDecision | None:
        if self.active_cycle_id is None or self.cycle_warned or not warning_enabled:
            return None

        star_class = normalize_star_class(target.star_class) if target else None
        if star_class in KGBFOAM_CLASSES:
            return None

        profile = get_star_class_profile(star_class)
        if profile is not None:
            self.cycle_warned = True
            return JumpWarningDecision(
                cycle_id=self.active_cycle_id,
                kind="known",
                trigger=trigger,
                target_name=target.name if target else None,
                star_class=profile.canonical_class,
                profile=profile,
            )

        if not unknown_warning_enabled:
            return None
        self.cycle_warned = True
        return JumpWarningDecision(
            cycle_id=self.active_cycle_id,
            kind="unknown",
            trigger=trigger,
            target_name=target.name if target else None,
            star_class=star_class,
            profile=None,
        )

    def process(
        self,
        event: Event,
        *,
        warning_enabled: bool,
        unknown_warning_enabled: bool,
    ) -> JumpWarningDecision | None:
        if isinstance(event, GameEvent):
            event_name = event.content.get("event")
            if event_name == "FSDTarget":
                self.current_target = JumpTarget(
                    name=self._name(event.content.get("Name")),
                    system_address=self._address(event.content.get("SystemAddress")),
                    star_class=event.content.get("StarClass"),
                )
                return None

            if event_name == "StartJump":
                if event.content.get("JumpType") != "Hyperspace":
                    self.phase = "countdown"
                    self.charge_kind = "supercruise"
                    return None
                if self.active_cycle_id is None:
                    self._begin_cycle("hyperspace")
                self.phase = "countdown"
                self.charge_kind = "hyperspace"
                start_target = JumpTarget(
                    name=self._name(event.content.get("StarSystem")),
                    system_address=self._address(event.content.get("SystemAddress")),
                    star_class=event.content.get("StarClass"),
                )
                return self._decision_for_target(
                    start_target,
                    trigger="start_jump",
                    warning_enabled=warning_enabled,
                    unknown_warning_enabled=unknown_warning_enabled,
                )

            if event_name == "FSDJump":
                self.charge_active = False
                self.charge_kind = None
                self.active_cycle_id = None
                self.cycle_warned = False
                self.phase = "completed"
                return None

            if event_name in {"LoadGame", "Shutdown"}:
                self.current_target = None
                self.charge_active = False
                self.charge_kind = None
                self.active_cycle_id = None
                self.cycle_warned = False
                self.phase = "idle"
                return None

            # NavRoute and NavRouteClear intentionally have no warning side
            # effects.  FSDTarget remains authoritative for a selected hop.
            return None

        if not isinstance(event, StatusEvent):
            return None

        event_name = event.status.get("event")
        if event_name == "Status":
            flags = event.status.get("flags")
            if not isinstance(flags, dict):
                return None
            is_charging = bool(flags.get("FsdCharging"))
            if not is_charging:
                self.charge_active = False
                if self.phase == "charging":
                    self.phase = "idle"
                return None
            if self.charge_active:
                return None

            self.charge_active = True
            flags2 = event.status.get("flags2")
            hyperdrive_flag: bool | None = None
            if isinstance(flags2, dict) and "FsdHyperdriveCharging" in flags2:
                hyperdrive_flag = bool(flags2.get("FsdHyperdriveCharging"))
            kind: Literal["hyperspace", "supercruise", "unknown"] = (
                "hyperspace" if hyperdrive_flag is True
                else "supercruise" if hyperdrive_flag is False
                else "unknown"
            )
            self._begin_cycle(kind)
            if kind != "hyperspace":
                return None
            return self._decision_for_target(
                self._target_for_status(event.status),
                trigger="fsd_charging",
                warning_enabled=warning_enabled,
                unknown_warning_enabled=unknown_warning_enabled,
            )

        if event_name == "FsdCharging":
            if self.charge_active:
                return None
            self.charge_active = True
            jump_type = event.status.get("JumpType")
            kind = (
                "hyperspace" if jump_type == "Hyperspace"
                else "supercruise" if jump_type == "Supercruise"
                else "unknown"
            )
            self._begin_cycle(kind)
            if kind != "hyperspace":
                return None
            return self._decision_for_target(
                self.current_target,
                trigger="fsd_charging",
                warning_enabled=warning_enabled,
                unknown_warning_enabled=unknown_warning_enabled,
            )

        return None
